# syntax = docker/dockerfile:1

# Make sure RUBY_VERSION matches the Ruby version in .ruby-version and Gemfile
ARG RUBY_VERSION=3.1.4
FROM registry.docker.com/library/ruby:$RUBY_VERSION as base

LABEL maintainer="ryan.brilliant.nirwana@gmail.com"

WORKDIR /usr/src/app

FROM base as build

# Ensure latest packages for Yarn
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=true apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list

RUN apt-get update -yqq && \
    apt-get install -yqq --no-install-recommends \
    build-essential \
    nodejs \
    vim \
    yarn

COPY Gemfile* .

RUN bundle install

COPY . .

CMD ["bin/rails", "s", "-b", "0.0.0.0"]
